#macro VIEW_WIDTH 1600//1280//1280//1440 16//(view_get_wport(view_camera[0]))
#macro VIEW_HEIGHT 900//720//720 //9(view_get_hport(view_camera[0]))
#macro CAMERA_WIDTH_RATIO 16
#macro CAMERA_HEIGHT_RATIO 9

#macro CAMERA_SMALLEST_FACTOR 4

#macro VIEW_SIZE_RATIO VIEW_WIDTH / CAMERA_WIDTH_RATIO


#macro GUI_MAP_MARGIN VIEW_WIDTH*0.1
#macro GUI_MAP_TOP_MARGIN VIEW_HEIGHT*0.05
#macro GUI_MAP_BOT_MARGIN VIEW_HEIGHT*0.05

#macro GUI_SEQUENCE_WIDTH VIEW_WIDTH*0.4
#macro GUI_SEQUENCE_HEIGHT VIEW_HEIGHT*0.1

#macro LARGEST_SPRITE_HEIGHT 16